title: Katharine Robertson
logo: assets/headshot_circle.png
description: Hi! Thanks for stopping by my docs portfolio. \
My goal is to keep things simple and not make a user feel like they wandered off into a maze of word salad. 
#show_downloads:
theme: jekyll-theme-minimal
