title: Katharine Robertson
logo: assets/headshot_circle.png
description: Hi, I'm Katharine, and welcome to my portfolio! Word salad and non-inclusive jargon are not welcome.
#show_downloads:
theme: jekyll-theme-minimal
