title: Katharine Robertson
logo: assets/headshot_circle.png
description: Technical writer and fan of user-friendly and inclusive documentation. Welcome to my portfolio! 
#show_downloads:
theme: jekyll-theme-minimal
