title: Katharine Robertson
logo: assets/headshot_circle.png
description: Hi! Welcome to my portfolio. \
I like a simple and inclusive user journey. Word salad and jargon not allowed.
#show_downloads:
theme: jekyll-theme-minimal
